basic math and statistics

In [2]:
import numpy as np
from numpy.random import randn

In [2]:
np.set_printoptions(precision=2)

In [3]:
# create arrays
# create arrays using a list
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [4]:
b=np.array([[10,20,20],[40,50,60]])
b

array([[10, 20, 20],
       [40, 50, 60]])

In [8]:
# creating arrays via assignment
np.random.seed(25)
c = 36*np.random.randn(6)
c

array([  8.22,  36.97, -30.23, -21.28, -34.45,  -8.  ])

In [6]:
d = np.arange(1,35)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [9]:
#performing arithmetic on arrays
a*10

array([10, 20, 30, 40, 50, 60])

In [10]:
c+a

array([  9.22,  38.97, -27.23, -17.28, -29.45,  -2.  ])

In [11]:
c-a

array([  7.22,  34.97, -33.23, -25.28, -39.45, -14.  ])

In [12]:
c*a

array([   8.22,   73.94,  -90.68,  -85.13, -172.24,  -48.02])

In [13]:
c/a

array([  8.22,  18.48, -10.08,  -5.32,  -6.89,  -1.33])

In [14]:
#multiplying matrics and basic linear algebra
np.set_printoptions(precision=2)

In [15]:
aa = np.array([[2.,4.,6.],[1.,3.,5.],[10.,20.,30.,]])
aa

array([[ 2.,  4.,  6.],
       [ 1.,  3.,  5.],
       [10., 20., 30.]])

In [17]:
bb = np.array([[0.,1.,2.],[3.,4.,5.],[6.,7.,8.]])
bb

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [18]:
aa*bb

array([[  0.,   4.,  12.],
       [  3.,  12.,  25.],
       [ 60., 140., 240.]])

In [19]:
aa/bb

/home/ood.discovery.neu.edu/software/anaconda3/2019.10/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[ inf, 4.  , 3.  ],
       [0.33, 0.75, 1.  ],
       [1.67, 2.86, 3.75]])

In [20]:
np.dot(aa,bb)

array([[ 48.,  60.,  72.],
       [ 39.,  48.,  57.],
       [240., 300., 360.]])

In [3]:
a1= np.array([[1.,3.],[2.,4.]])
b1= np.array([[5.,8.],[7.,9.]])
a1*b1

array([[ 5., 24.],
       [14., 36.]])

In [4]:
3+16+63

82

In [4]:
xx=np.array([[7.,9.],[5.,12.]])
yy=np.array([[2.,8.],[7.,4.]])
xx*yy

array([[14., 72.],
       [35., 48.]])

In [5]:
np.dot(xx,yy)

array([[77., 92.],
       [94., 88.]])

In [6]:
ax = np.array([[1.,2.,3.],[4.,5.,6.]])
ay = np.array([[10.,11.],[20.,21.],[30.,31.]])
np.dot(ax,ay)

array([[140., 146.],
       [320., 335.]])

In [7]:
a=np.array([10,15,20])
b=([5,7,9])
(a-b)*7

array([35, 56, 77])