In [1]:
import numpy as np
import pandas as pd

from pandas import Series, DataFrame
 

import sklearn 
from sklearn import datasets

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

from sklearn. linear_model import Perceptron

In [2]:
iris=datasets.load_iris()
X = iris.data
y = iris.target

X[0:10,]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [3]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [6]:
standardize = StandardScaler()

standardized_x_test = standardize.fit_transform(x_test)
standardized_x_train = standardize.fit_transform(x_train)

In [7]:
 standardized_x_test[0:10]

array([[-1.03226633, -1.03448446, -0.07506659,  0.0701215 ],
       [ 0.99256378,  0.05444655,  0.60053274,  1.25342187],
       [ 0.03970255, -0.76225171, -0.01876665, -0.06135632],
       [-1.15137398,  1.96007582, -1.42626526, -1.3761345 ],
       [ 0.27791786, -0.76225171,  0.60053274,  0.20159932],
       [ 0.75434847, -0.2177862 ,  0.65683268,  1.25342187],
       [-1.15137398,  1.68784307, -1.42626526, -1.24465668],
       [-0.19851276,  0.3266793 ,  0.43163291,  0.59603278],
       [ 1.945425  , -1.30671722,  1.61393174,  1.25342187],
       [ 1.945425  , -0.76225171,  1.50133185,  0.85898841]])

In [10]:
perceptron = Perceptron(max_iter=50, eta0=0.15, tol=1e-3, random_state=15)

perceptron.fit(standardized_x_train, y_train.ravel())

Perceptron(eta0=0.15, max_iter=50, random_state=15)

In [12]:
y_pred = perceptron.predict(standardized_x_test)

In [13]:
print(y_pred)

[1 2 1 0 1 2 0 1 1 1 0 2 1 1 2 2 0 1 1 1 1 0 1 1 1 0 1 0 0 1]


In [14]:
print(y_test)

[1 2 1 0 2 2 0 1 2 2 0 2 1 1 2 2 0 1 1 1 2 0 1 1 1 0 2 0 0 2]


In [16]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       0.65      1.00      0.79        11
           2       1.00      0.45      0.62        11

    accuracy                           0.80        30
   macro avg       0.88      0.82      0.80        30
weighted avg       0.87      0.80      0.78        30

